version: 0.2

phases: 
    pre_build: 
        commands:
            - echo Test code...

    build: 
        commands: 
            - echo tag is $IMAGE_TAG

    post_build: 
        commands:
            - echo Build completed on `date`

